name: Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Deploy to server
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_HOST_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            echo "${{ secrets.GITHUB_TOKEN }}" \
              | docker login ghcr.io \
                --username "${{ github.actor }}" \
                --password-stdin
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop vermon || true
            docker rm vermon || true
            mkdir -p ~/vermon
            echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" > ~/vermon/.env
            docker run -d --name vermon -p 4000:3000 --restart unless-stopped --env-file ~/vermon/.env ghcr.io/${{ github.repository }}:latest
          EOF
